# Generated by Django 3.0.6 on 2021-01-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0013_auto_20210114_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('posongvi', '뽀송비 학생'), ('bluemover', '블루무버'), ('applicant', '블루무버 희망자')], max_length=50),
        ),
    ]
