# Generated by Django 3.0.6 on 2021-01-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0032_auto_20210118_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
