# Generated by Django 3.0.6 on 2021-01-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0038_auto_20210122_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('guest', '게스트'), ('bluemover', '블루무버')], max_length=50),
        ),
    ]
