# Generated by Django 3.0.6 on 2021-04-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0053_auto_20210422_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recomment',
        ),
    ]
