# Generated by Django 3.0.6 on 2021-04-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0058_auto_20210425_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mention_flag',
            field=models.BooleanField(default=False),
        ),
    ]
