# Generated by Django 3.0.6 on 2021-04-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0059_comment_mention_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='mention_flag',
        ),
        migrations.AddField(
            model_name='comment',
            name='mentioned_users',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
