# Generated by Django 3.0.6 on 2021-04-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0060_auto_20210426_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mentioned_users',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
