# Generated by Django 3.0.6 on 2021-04-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0061_auto_20210426_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mentioned_users',
            field=models.TextField(blank=True, null=True),
        ),
    ]
