# Generated by Django 3.0.6 on 2021-04-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0064_auto_20210426_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='channel_id',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='channel_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('bluemover', '블루무버'), ('guest', '게스트')], max_length=50),
        ),
    ]
