# Generated by Django 3.0.6 on 2021-01-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/profile-picture-default.png', upload_to='images/', verbose_name='Profile Picture'),
        ),
    ]
