# Generated by Django 3.0.6 on 2021-01-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210102_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
