# Generated by Django 3.0.6 on 2021-01-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='realname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
