# Generated by Django 3.0.6 on 2021-05-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210514_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notion_user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
