# Generated by Django 3.0.6 on 2021-01-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210116_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='real_name',
        ),
    ]
