# Generated by Django 3.0.6 on 2021-01-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_update_flag',
            field=models.BooleanField(default=False),
        ),
    ]
