# Generated by Django 3.0.6 on 2021-01-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_avatar_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_src',
        ),
    ]
