# Generated by Django 3.0.6 on 2021-01-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_avatar_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name_update_flag',
            new_name='info_update_flag',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
