# Generated by Django 3.0.6 on 2021-04-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_slack_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sub_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
