# Generated by Django 3.0.6 on 2021-01-06 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('applicant', '블루무버 희망자'), ('posongvi', '뽀송비 학생'), ('bluemover', '블루무버')], max_length=50)),
                ('content', models.TextField()),
                ('content_update_flag', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('deadline', models.DateField()),
                ('deadline_update_flag', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.Box')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_favorite_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'box')},
            },
        ),
        migrations.AddField(
            model_name='box',
            name='box_favorite_user_set',
            field=models.ManyToManyField(blank=True, related_name='box_favorite_user_set', through='box.Favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='box',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
