# Generated by Django 3.0.6 on 2021-05-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_auto_20210514_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
