# Generated by Django 3.0.6 on 2021-05-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_auto_20210504_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='mimetype',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
