# Generated by Django 3.0.6 on 2021-05-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_auto_20210514_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='notion_page_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('bluemover', '블루무버'), ('guest', '게스트')], max_length=50),
        ),
    ]
