# Generated by Django 3.0.6 on 2021-05-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_doc_mimetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='document_mimetype',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
