# Generated by Django 3.0.6 on 2021-01-06 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('box', '0003_auto_20210104_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('posongvi', '뽀송비 학생'), ('bluemover', '블루무버'), ('applicant', '블루무버 희망자')], max_length=50),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.Box')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_favorite_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'box')},
            },
        ),
        migrations.AddField(
            model_name='box',
            name='box_favorite_user_set',
            field=models.ManyToManyField(blank=True, related_name='box_favorite_user_set', through='box.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
