# Generated by Django 3.0.6 on 2021-05-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0004_auto_20210515_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='notion_page_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
