# Generated by Django 3.0.6 on 2021-01-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0004_auto_20210109_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('posongvi', '뽀송비 학생'), ('bluemover', '블루무버'), ('applicant', '블루무버 희망자')], max_length=50),
        ),
        migrations.AlterField(
            model_name='box',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
