# Generated by Django 3.0.6 on 2021-01-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0008_auto_20210103_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('applicant', '블루무버 희망자'), ('posongvi', '뽀송비 학생'), ('bluemover', '블루무버')], max_length=50),
        ),
        migrations.AlterField(
            model_name='box',
            name='image',
            field=models.ImageField(blank=True, default='images/box-image-default.png', null=True, upload_to='images/'),
        ),
    ]
