# Generated by Django 3.0.6 on 2021-01-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0011_auto_20210103_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/box-image-default.png', null=True, upload_to='images/'),
        ),
    ]
