# Generated by Django 3.0.6 on 2021-01-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0016_auto_20210114_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='submittee',
            new_name='user',
        ),
        migrations.AddField(
            model_name='doc',
            name='submit_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('bluemover', '블루무버'), ('posongvi', '뽀송비 학생'), ('applicant', '블루무버 희망자')], max_length=50),
        ),
    ]
