# Generated by Django 3.0.6 on 2021-01-14 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('box', '0017_auto_20210114_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='box_doc_user_set',
            field=models.ManyToManyField(blank=True, related_name='box_doc_user_set', through='box.Doc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('applicant', '블루무버 희망자'), ('bluemover', '블루무버'), ('posongvi', '뽀송비 학생')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='doc',
            unique_together={('user', 'box')},
        ),
    ]
