# Generated by Django 3.0.6 on 2021-01-14 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('box', '0018_auto_20210114_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('applicant', '블루무버 희망자'), ('posongvi', '뽀송비 학생'), ('bluemover', '블루무버')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doc',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.Box'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_doc_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
