# Generated by Django 3.0.6 on 2021-01-15 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('box', '0020_auto_20210115_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='box_doc_user_set',
        ),
        migrations.AlterField(
            model_name='doc',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='box.Box'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='doc',
            unique_together=set(),
        ),
    ]
