# Generated by Django 3.0.6 on 2021-01-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0021_auto_20210115_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('bluemover', '블루무버'), ('posongvi', '뽀송비 학생'), ('applicant', '블루무버 희망자')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
