# Generated by Django 3.0.6 on 2021-01-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0023_auto_20210103_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='deadline_check',
            new_name='deadline_flag',
        ),
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('applicant', '블루무버 희망자'), ('bluemover', '블루무버'), ('posongvi', '뽀송비 학생')], max_length=50),
        ),
    ]
