# Generated by Django 3.0.6 on 2021-01-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0024_auto_20210115_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='box_permission_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='user_permission_id',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
