# Generated by Django 3.0.6 on 2021-01-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0029_auto_20210103_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='deadline_flag',
            field=models.BooleanField(default=False),
        ),
    ]
