# Generated by Django 3.0.6 on 2021-01-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0031_auto_20210116_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='examiner_email',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
