# Generated by Django 3.0.6 on 2021-01-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0031_auto_20210104_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='content_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('applicant', '블루무버 희망자'), ('posongvi', '뽀송비 학생'), ('bluemover', '블루무버')], max_length=50),
        ),
    ]
