# Generated by Django 3.0.6 on 2021-01-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0033_auto_20210117_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='examiner_email',
        ),
    ]
