# Generated by Django 3.0.6 on 2021-01-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0034_remove_box_examiner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('applicant', '블루무버 희망자'), ('bluemover', '블루무버'), ('posongvi', '뽀송비 학생')], max_length=50),
        ),
    ]
