# Generated by Django 3.0.6 on 2021-01-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0037_auto_20210118_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='thumbnail_src',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
