# Generated by Django 3.0.6 on 2021-01-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0038_doc_thumbnail_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='thumbnail_src',
        ),
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('guest', '게스트'), ('bluemover', '블루무버')], max_length=50),
        ),
    ]
