# Generated by Django 3.0.6 on 2021-01-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0040_auto_20210121_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='creation_datetime',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc',
            name='return_datetime',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc',
            name='return_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doc',
            name='submission_datetime',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
