# Generated by Django 3.0.6 on 2021-01-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0042_auto_20210122_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='reject_reason',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('bluemover', '블루무버'), ('guest', '게스트')], max_length=50),
        ),
    ]
