# Generated by Django 3.0.6 on 2021-01-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0043_auto_20210122_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('guest', '게스트'), ('bluemover', '블루무버')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doc',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
