# Generated by Django 3.0.6 on 2021-01-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0045_auto_20210122_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='creation_datetime',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='doc',
            old_name='rejection_datetime',
            new_name='rejection_date',
        ),
        migrations.RenameField(
            model_name='doc',
            old_name='return_datetime',
            new_name='return_date',
        ),
        migrations.RenameField(
            model_name='doc',
            old_name='submission_datetime',
            new_name='submission_date',
        ),
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('guest', '게스트'), ('bluemover', '블루무버')], max_length=50),
        ),
    ]
