# Generated by Django 3.0.6 on 2021-01-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0047_auto_20210123_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='channel_id',
            field=models.CharField(default='C01L8PETS5S', max_length=50),
            preserve_default=False,
        ),
    ]
