# Generated by Django 3.0.6 on 2021-01-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0051_auto_20210130_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='delete_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='file_id',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doc',
            name='folder',
            field=models.CharField(blank=True, choices=[('0AIsg5YLQSTjaUk9PVA', '6 운영'), ('0ADNIg7OWApdMUk9PVA', '3 배프콘텐츠'), ('0ADF4LPECMczOUk9PVA', '2 뽀송비')], max_length=50, null=True),
        ),
    ]
