# Generated by Django 3.0.6 on 2021-01-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0052_auto_20210130_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('bluemover', '블루무버'), ('guest', '게스트')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doc',
            name='folder',
            field=models.CharField(blank=True, choices=[('0AIsg5YLQSTjaUk9PVA', '6 운영'), ('0ADF4LPECMczOUk9PVA', '2 뽀송비'), ('0ADNIg7OWApdMUk9PVA', '3 배프콘텐츠')], max_length=50, null=True),
        ),
    ]
