# Generated by Django 3.0.6 on 2021-01-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0053_auto_20210131_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='channel_id_text',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('guest', '게스트'), ('bluemover', '블루무버')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doc',
            name='avatar_src',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='folder',
            field=models.CharField(blank=True, choices=[('0AIsg5YLQSTjaUk9PVA', '5 운영'), ('0ADNIg7OWApdMUk9PVA', '3 콘텐츠사업'), ('0ADF4LPECMczOUk9PVA', '2 교육사업')], max_length=50, null=True),
        ),
    ]
