# Generated by Django 3.0.6 on 2021-02-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0060_auto_20210201_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='folder',
        ),
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('bluemover', '블루무버'), ('guest', '게스트')], max_length=50),
        ),
    ]
