# Generated by Django 3.0.6 on 2021-02-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0061_auto_20210201_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('guest', '게스트'), ('bluemover', '블루무버')], max_length=50),
        ),
        migrations.AlterField(
            model_name='box',
            name='folder_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
