# Generated by Django 3.0.6 on 2021-02-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0064_auto_20210205_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.AddField(
            model_name='box',
            name='drive_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
