# Generated by Django 3.0.6 on 2021-02-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0065_auto_20210207_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='prefix',
            new_name='folder_name',
        ),
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('bluemover', '블루무버'), ('guest', '게스트')], max_length=50),
        ),
    ]
