# Generated by Django 3.0.6 on 2021-02-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0066_auto_20210207_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='channel_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
