# Generated by Django 3.0.6 on 2021-04-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0067_box_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('guest', '게스트'), ('bluemover', '블루무버')], max_length=50),
        ),
    ]
