# Generated by Django 3.0.6 on 2021-04-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0068_auto_20210422_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='official_template_flag',
            field=models.BooleanField(default=False),
        ),
    ]
