# Generated by Django 3.0.6 on 2021-04-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0069_box_official_template_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='document_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('bluemover', '블루무버'), ('guest', '게스트')], max_length=50),
        ),
    ]
