# Generated by Django 3.0.6 on 2021-04-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0071_auto_20210424_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('bluemover', '블루무버'), ('guest', '게스트')], max_length=50),
        ),
    ]
