# Generated by Django 3.0.6 on 2021-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0074_auto_20210426_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='forler_prefix',
            new_name='folder_prefix',
        ),
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.CharField(choices=[('guest', '게스트'), ('bluemover', '블루무버')], max_length=50),
        ),
    ]
